spring:
    data:
        mongodb:
            host: localhost
            port: 27017
            database: chatdb
            
    web:
        resources:
            static-locations: classpath:/static/
            add-mappings: true

    mvc:
        static-path-pattern: /static/** 
             